name: 'SemVer Action'
description: 'Increase SemVer'
inputs:
  repo_owner:
    description: 'Name github repo owner or organization'
    required: true
  repo_name:
    description: 'Name github repo'
    required: true
  github_token:
    description: 'Github token for making POST api request'
    required: true
  type:
    description: 'Type of version statement owner (helm or nodejs)'
    required: true
  semver:
    description: 'Type of version number (major, minor, patch)'
    required: true
runs:
  using: composite
  steps:
    - name: Install yq
      uses: Makepad-fr/setup-yq-action@v1.0.0
      with:
        version: '4.6.0'

    - name: 'Setup jq'
      uses: dcarbone/install-jq-action@v3
      with:
          version: '1.7'

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Make script executble 
      run: chmod +x deploy_by_tag.sh
      shell: bash

    - name: Run updater
      run: deploy_by_tag.sh
      shell: bash
      env:
        repo_owner: ${{ inputs.repo_owner }}
        repo_name: ${{ inputs.repo_name }}
        github_token: ${{ inputs.github_token }}
        type: ${{ inputs.type }}
        semver: ${{ inputs.semver }}